include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    avoid_print: true
    always_use_package_imports: true



